version: 2
jobs:
  build:
    working_directory: ~/grow
    docker:
      - image: grow/base:latest
    steps:
      - checkout

      - restore_cache:
          keys:
            - grow-cache-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: Grow Intall
          command: grow install

      - save_cache:
          key: grow-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - extensions
            - node_modules

      - run:
          name: Test Build
          command: grow build
